config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: [:show, :destroy]


  resources :questionnaires, only: [:index, :show, :new, :create]
  resources :questions do
    resources :answers, only: [:new, :create, :edit, :update]
  end
  resources :movies, only: [:create]

  resources :watched_movies, only: [:create, :update] do
    resources :ratings, only: [:create]
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :user, optional: true
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
end

app/controllers/questionnaires_controller.rb
# Using free API: https://www.themoviedb.org/

require 'uri'
require 'net/http'
require 'json'

class QuestionnairesController < ApplicationController
#  before_action :authenticate_user!, except: [:new, :create]
  before_action :set_questionnaire, only: [:show]
  before_action :set_first_question, only: [:create, :show]
  before_action :set_answers, only: [:show]

  def index
    @questionnaires = Questionnaire.all
  end

  def show
    # search 1: based on main criteria => return movie_id
    @movie_ids = search_main_params
    @popular_movies_ids = popular_movies

    # search 2: based on movie_id => return more details (e.g. runtime, actors etc.)
    if @movie_ids.count >= 3
      @movies = search_by_movie_id(@movie_ids)
      puts "Initial API search successful"
    else
      @movies = search_by_movie_id(@popular_movies_ids)
      puts "Initial API search failed: returns default popular movies"
    end

    # store it in the results of the questionnaire to access it later in the watchlist
    @questionnaire.update(results: @movies)
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def create
    # raise
    @questionnaire = Questionnaire.new(title: Time.now)
    @questionnaire.user = current_user

    if @questionnaire.save
      @question.questionnaire = @questionnaire
      @question.save

      redirect_to new_question_answer_path(@question)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  ## START: ALGORYTHM METHODS

  def complete_list(movie)
    puts "Movie: #{movie['id']} - #{movie['title']} #{@movie['counter']}"
  end

  def search_setup(url, api_key)
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["Authorization"] = "Bearer #{api_key}"

    response = http.request(request)

    # Parse the response body and extract the necessary information
    JSON.parse(response.read_body)
  end

  def popular_movies
    genre = [28, 12, 35, 10751, 9648, 10749, 878].sample
    # Error Handling Path: returns 10 current popular movies if no results found
    api_key = ENV['TMDB_KEY']
    url = URI("https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&primary_release_date.gte=2010&primary_release_date.lte=2020&with_genres=#{genre}&vote_average.gte=7")
    result = search_setup(url, api_key)
    movie_ids = []
    # Check if any results are returned
    if result['results'].any?
      @generated_popular_movies = result['results'].each do |movie|
        movie_ids << movie['id']
      end
    else
      puts "No movie found, please take questionnaire again"
    end
    return movie_ids
  end

  def search_main_params
    # Returns an array of movie_ids based on basic search (date, genre etc.)
    api_key = ENV['TMDB_KEY']
    url = URI("https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&primary_release_date.gte=#{year_start}&primary_release_date.lte=#{year_end}&with_genres=#{genre_id}&vote_average.gte=#{vote_average}")
    result = search_setup(url, api_key)
    movie_ids = []
    # Check if any results are returned
    if result['results'].any?
      @generated_movies = result['results'].each do |movie|
        movie_ids << movie['id']
      end
    else
      puts "No movie found, please take questionnaire again"
    end
    return movie_ids
  end

  def search_by_movie_id(movie_ids)
    @movies = []
    # Debug user answers
    movie_ids.each do |id|
      # Returns movies with main data
      api_key = ENV['TMDB_KEY']
      url = URI("https://api.themoviedb.org/3/movie/#{id}?language=en-US")
      @movie = search_setup(url, api_key)

      # Returns credits (cast and crew)
      url_crew = URI("https://api.themoviedb.org/3/movie/#{id}/credits?language=en-US")
      result = search_setup(url_crew, api_key)
      @crew = result['crew']
      @cast = result['cast']

      # Show movie info in modal
      director = @crew.find { |member| member['job'] == "Director" }
      @movie['director'] = director['name'] if director
      # to be refactored with loop/check if exists (not working for documentaries)
      @movie['actor_first'] = result['cast'][0]['name'] if result['cast'].present? && result['cast'][0]['name'].present?
      @movie['actor_second'] = result['cast'][1]['name'] if result['cast'][1].present? && result['cast'][1]['name'].present?
      @movie['poster_path'] = "https://image.tmdb.org/t/p/w342#{@movie['poster_path']}"

      # Weight each user criteria
      @movie['counter'] = 0
      # Director
      @movie['counter'] += 1 if @answers[2].content.present? && @crew.any? { |member| member['name'].downcase.include?(@answers[2].content.downcase) }
      # Actors
      @movie['counter'] += 1 if @answers[3].content.present? && @cast.any? { |member| member['name'].downcase.include?(@answers[3].content.downcase) }
      # Runtime
      @movie['counter'] += 1 if @movie['runtime'] < @answers[4].content.to_i

      @movies << @movie
      # see complete list of movies (not only 3 first)
      complete_list(@movie)
    end
    puts "ANSWERS: Genre: #{@answers[0].content} Decade: #{@answers[1].content} Director: #{@answers[2].content} Actor: #{@answers[3].content} Runtime_max: #{@answers[4].content} "
    @movies.sort_by.with_index { |movie, index| [-movie['counter'], index] }
  end

  def year_start
    if @answers[1].content.present?
      year = @answers[1].content
    else
      year = 1980
    end
    "#{year}-01-01"
  end

  def year_end
    if  @answers[1].content.present?
      year = @answers[1].content.to_i + 9
    else
      year = (Date.today.year) - 1
    end
    "#{year}-12-31"
  end

  def genre_id
    if @answers[0].content.present?
      @answers[0].content.gsub(/(?<=\S)\s+/, ',')
    else
      # select randomly one of this popular genres (ex: horror excluded)
      genres = [28, 12, 35, 10751, 9648, 10749, 878]
      genres.sample
    end
    # genres_id.join(",") # to be added when transformed into multiple select!
  end

  def vote_average
    # Temp value below
    6.5
  end

  def set_answers
    questions = @questionnaire.questions
    @answers = []
    @answers << questions.find{ |question| question.content == Question::QUESTIONS[:genre] }.answer
    @answers << questions.find{ |question| question.content == Question::QUESTIONS[:decade] }.answer
    @answers << questions.find{ |question| question.content == Question::QUESTIONS[:director] }.answer
    @answers << questions.find{ |question| question.content == Question::QUESTIONS[:actor] }.answer
    @answers << questions.find{ |question| question.content == Question::QUESTIONS[:runtime] }.answer
    @answers
  end

  ## END: ALGORYTHM METHODS

  def questionnaire_params
    params.require(:questionnaire).permit(:title)
  end

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  def set_first_question
    @question = Question.new(content: Question::QUESTIONS[:genre])
  end
end

app/views/questionnaires/index.html.erb
<div class="container mt-3">
  <h1>Questionnaires Index (testing)</h1>
  <%= link_to "Start", questionnaires_path, data: { turbo_method: :post }, class: "btn btn-primary" %>
  <h2 class="mt-3">My tests:</h2>
  <% @questionnaires.each do |questionnaire|  %>
    <div>
      <%= link_to questionnaire.title, questionnaire_path(questionnaire) %>
    </div>
  <% end %>
</div>

app/views/questionnaires/new.html.erb
<div class="container mt-3">
  <h1>New Questionnaire</h1>
  <%= simple_form_for @questionnaire do |f| %>
    <%= f.input :title %> 
    <%= f.submit "Next", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/questionnaires/show.html.erb
<div class="container">

  <div class="d-flex justify-content-center">
    <% if @movie_ids.count < 3 %>
    <p>We see you have unique tastes! We haven't found your exact match yet, but we think you might enjoy these!
    <% end %>
  </div>

  <!-- Modal main card-->

  <div class="modal-container">
    <div class="modal fade" id="first" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <img class="modal-poster" src=<%= @movies.first['poster_path']%>>
            <h2 class="modal-title" id="staticBackdropLabel"><%= @movies.first['title']%> (<%= @movies.first['release_date'][0, 4]%>)</h2>
             <p><div class="genre-flex">
                <% @movies.first['genres'].each do |genre| %>
                 <div class="genres-tag"> <%= genre['name'] %></div>
                <% end %></div>
              <div class="modal-infos">
              <p><strong> Directed by </strong> <%= @movies.first['director']%></p>
              <p><strong> Starring </strong><%= @movies.first['actor_first']%>, <%= @movies.first['actor_second']%></p>
              <p><strong><%= @movies.first['runtime']%> minutes</strong></p></div>
              <br>
            <p class="overview-text"><%= @movies.first['overview']%></p>
          </div>
          <div class="modal-footer">
            <div class="d-flex justify-content-center button-container">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
            <% if user_signed_in? %>
            <div class="d-flex justify-content-center button-container">
              <div data-controller="add-to-watchlist" data-add-to-watchlist-movie-value="<%= @movies.first.to_json %>">
                <%= button_to "I'm watching this", movies_path, data: { action: "click->add-to-watchlist#add" }, class: "button-submit" %>
              </div>
            </div>
            <% else %>
              <div class="d-flex justify-content-center button-container">
                <%= link_to "I'm watching this", new_user_registration_path, class: "button-submit" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<!---modal left card---->


  <div class="modal-container">
      <div class="modal fade" id="second" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
              <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="back"></button> %>
            <div class="modal-body">
              <img class="modal-poster" src=<%= @movies.second['poster_path']%>>
              <h2 class="modal-title" id="staticBackdropLabel"><%= @movies.second['title']%> (<%= @movies.second['release_date'][0, 4]%>)</h2>
               <p><div class="genre-flex">
                <% @movies.second['genres'].each do |genre| %>
                 <div class="genres-tag"> <%= genre['name'] %></div>
                <% end %></div></p>
                <div class="modal-infos">
                <p><strong> Directed by</strong> <%= @movies.second['director']%></p>
                <p><strong> Starring </strong><%= @movies.second['actor_first']%>, <%= @movies.second['actor_second']%></p>
                <p><strong><%= @movies.second['runtime']%> minutes</strong></p></div>
                <br>
              <p class="overview-text"><%= @movies.second['overview']%></p>
            </div>
            <div class="modal-footer">
              <div class="d-flex justify-content-center button-container">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
              <% if user_signed_in? %>
              <div class="d-flex justify-content-center button-container">
                <div data-controller="add-to-watchlist" data-add-to-watchlist-movie-value="<%= @movies.second.to_json %>">
                  <%= button_to "I'm watching this", movies_path, data: { action: "click->add-to-watchlist#add" }, class: "button-submit" %>
                </div>
              </div>
              <% else %>
                <div class="d-flex justify-content-center button-container">
                  <%= link_to "I'm watching this", new_user_registration_path, class: "button-submit"%>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>

<!---modal right card---->


  <div class="modal-container">
      <div class="modal fade" id="third" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
              <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="back"></button> %>
            <div class="modal-body">
              <img class="modal-poster" src=<%= @movies.third['poster_path']%>>
              <h2 class="modal-title" id="staticBackdropLabel"><%= @movies.third['title']%> (<%= @movies.third['release_date'][0, 4]%>)</h2>
              <p><div class="genre-flex">
                <% @movies.third['genres'].each do |genre| %>
                 <div class="genres-tag"> <%= genre['name'] %></div>
                <% end %></div></p>
                <div class="modal-infos">
                <p><strong> Directed by </strong><%= @movies.third['director']%></p>
                <p><strong> Starring </strong><%= @movies.third['actor_first']%>, <%= @movies.third['actor_second']%></p>
                <p><strong><%= @movies.third['runtime']%> minutes</strong></p> </div>
                <br>
              <p class="overview-text"><%= @movies.third['overview']%></p>
            </div>
            <div class="modal-footer">
              <div class="d-flex justify-content-center button-container">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
              <% if user_signed_in? %>
              <div class="d-flex justify-content-center button-container">
                <div data-controller="add-to-watchlist" data-add-to-watchlist-movie-value="<%= @movies.third.to_json %>">
                  <%= button_to "I'm watching this", movies_path, data: { action: "click->add-to-watchlist#add" }, class: "button-submit" %>
                </div>
              </div>
              <% else %>
                <div class="d-flex justify-content-center button-container">
                  <%= link_to "I'm watching this", new_user_registration_path, class: "button-submit"%>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

<!------Left Card--------->

  <div class="row justify-content-center">
    <div class="col my-5 mx-2 result-movie-wrapper d-flex justify-content-center" data-controller="results" data-results-user-value="<%= user_signed_in? %>">
      <div class="result-movie-card <%= user_signed_in? ? "secondary-signed-up" : "secondary" %>" <%="data-bs-toggle=modal data-bs-target=#second"if user_signed_in?%>  data-action="mouseover->results#mouseEnters mouseleave->results#mouseLeaves">
        <% if !user_signed_in? %>
        <div id="revealText" data-results-target="revealText" class="d-none">
          <p>Never see the same movie twice, get more personalized recommendations based on your previous picks!</p>
          <div data-results-target="button">
            <%= link_to new_user_registration_path, class: "visitor-button" do %>
              Sign up!
            <% end %>
          </div>
          <p>
            <button class="revealButton" <%="data-bs-toggle=modal data-bs-target=#second"if !user_signed_in?%> data-results-target="revealButton" data-action="click->results#revealCard">Show movie anyway</button>
          </p>
        </div>
        <% end %>
        <div class="overlay" data-results-target="overlayFilter" style="background-image:url(<%= @movies.second['poster_path']%>); background-size: cover; background-position: center;"></div>
        <h2 class="mx-3 my-3 text-center"><%= @movies.second['title']%></h2>
        <div class="second-text-center d-flex flex-column align-items-center justify-content-center">
      </div>
    </div>
  </div>

<!------Middle Card--------->

  <div class="col my-3 d-flex justify-content-center">
    <div class="result-movie-card first-signed-up d-flex align-items-start flex-column" data-bs-toggle="modal" data-bs-target="#first" style="background-image:url(<%= @movies.first['poster_path']%>); background-size: cover; background-position: center;">
      <h2 class="mx-3 my-3 py-2"><%= @movies.first['title']%> (<%= @movies.first['release_date'][0, 4]%>)</h2>
      <div class="movie-info text-start mt-auto mx-3">
        <p> Runtime: <%= @movies.first['runtime']%> minutes</p>
        <p> Director: <%= @movies.first['director']%></p>
        <p> Actors: <%= @movies.first['actor_first']%>, <%= @movies.first['actor_second']%></p>
        <p> Genres:
          <% @movies.first['genres'].each do |genre| %>
            <%= genre['name'] %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

<!------Right Card--------->

  <div class="col my-5 mx-2 result-movie-wrapper d-flex justify-content-center" data-controller="results" data-results-user-value="<%= user_signed_in? %>" <%="data-bs-toggle=modal data-bs-target=#third"if user_signed_in?%>>
    <div class="result-movie-card <%= user_signed_in? ? "secondary-signed-up" : "secondary" %>" data-results-target="card" data-action="mouseover->results#mouseEnters mouseleave->results#mouseLeaves">
      <% if !user_signed_in? %>
      <div id="revealText" data-results-target="revealText" class="d-none">
        <p>Never see the same movie twice, get more personalized recommendations based on your previous picks!</p>
        <div data-results-target="button">
          <%= link_to new_user_registration_path, class: "visitor-button" do %>
            Sign up!
          <% end %>
        </div>
        <p>
          <button class="revealButton" data-results-target="revealButton" data-action="click->results#revealCard" <%="data-bs-toggle=modal data-bs-target=#third"if !user_signed_in?%>>Show movie anyway</button>
        </p>
      </div>
       <% end %>
      <div class="overlay" data-results-target="overlayFilter" style="background-image:url(<%= @movies.third['poster_path']%>);
        background-size: cover;
        background-position: center;">
      </div>
      <h2 class="mx-3 my-3"><%= @movies.third['title']%></h2>
      <div class="text-center d-flex align-items-center justify-content-center">
      </div>
    </div>
  </div>

<!-----Start again ----->

    <div class="row">
      <div class="d-flex justify-content-center">
        <div><%= button_to "Start again", questionnaires_path, data: { turbo_method: :post }, class: "visitor-button mb-4" %></div>
      </div>
    </div>
  </div>

</div>